<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Build;
use App\Models\Map;
use App\Models\Hero;
use App\Models\User;

class BuildSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        for($i = 0; $i < 150; $i++) {
            $build = new Build;
            $build->user_id = User::inRandomOrder()->first()->id;

            //this list dont have missing images...
            $hero = Hero::inRandomOrder()->first();

            $build->fill([
                'title' => 'First builds of the application!',
                'description' => 'i was generated by a seeder :)',
            ]);

            $build->hero_id = $hero->id;
            $build->save();

            $hero->talents = $hero->talents()->orderBy('id')->get()->groupBy('level');

            foreach($hero->talents as $level => $talents){
                $build->talents()->attach($talents->random());
            }

            $maps = Map::inRandomOrder()->limit(rand(1,5))->get();

            foreach($maps as $map){
                $build->maps()->attach($map);
            }
        }
    }
}
